### ISSUE TITLE
Server doesn't returns Identifiers

### ISSUE THREAD

**Issue by programmersmf** [prasifka/prach_dclink#1]
Recent days, I noticed that server doesn't return any players identifiers. 
Is the server side script fetch players identifier properly ?

**Comment by prasifka** [comment]
Hi,

I no longer actively update this script, but the identifier fetching should still work as expected since it relies on the native FiveM function [GetPlayerIdentifiers](https://docs.fivem.net/docs/scripting-reference/runtimes/lua/functions/GetPlayerIdentifiers/).

If the server isn't returning the identifiers, the issue is likely unrelated to the script and may stem from another problem in your server configuration or setup. I recommend verifying your server scripts and ensuring that everything is properly set up to use this function.

Let me know if you have any further questions!

**Comment by prasifka** [comment]
Hi,

I tested this on the current stable release of FiveM, and the script is still working as expected. The function `GetPlayerIdentifiers` is fetching identifiers without any issues. This further suggests that the problem lies somewhere else in your server setup or configuration.

Please double-check your server scripts and any dependencies that might affect this functionality. If you need further assistance, feel free to ask!
